name: Conventional changelog generator
description: Generate a changelog based on the conventional commit history for the latest tag.
inputs:
  repo-token:
    description: Github repository token
    required: true
  current-tag:
    description: Current tag selected to be the start of the changelog range
    required: false
  commit-types:
    description: Conventional commit type mapping
    required: true
  template-path:
    description: Changelog template
    required: false
  tag-regex:
    description: Specific regex to filter tags by and to version just between these (useful for SemVer labels)
    required: false
outputs:
  changelog:
    description: Generated changelog for the latest push version tag
runs:
  using: node20
  main: "dist/index.js"
